'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8806
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cornea.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property automation_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("automation_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property automation_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("automation_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property automation_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("automation_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property briefcase_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property briefcase_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property briefcase_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property building_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("building_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property building_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("building_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property building_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("building_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmark_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmark_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmark_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property construction_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("construction_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property construction_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("construction_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property construction_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("construction_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forwardbutton_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forwardbutton_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forwardbutton_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forwardbutton_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forwardbutton_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forwardbutton_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_161() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("link_161", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property link_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_481() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("link_481", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolder_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolder_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolder_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolder_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolder_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolder_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property person_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property person_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property person_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plusmath_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plusmath_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plusmath_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plusmath_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plusmath_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plusmath_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveall_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveall_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveall_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveall_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveall_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveall_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sort_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sort_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sort_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splitfiles_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splitfiles_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splitfiles_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splitfiles_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splitfiles_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splitfiles_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splitfiles_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splitfiles_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trashcan_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trashcan_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trashcan_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trashcan_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trashcan_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trashcan_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailable_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailable_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailable_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailable_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailable_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailable_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updownarrow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updownarrow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updownarrow_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updownarrow_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updownarrow_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updownarrow_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upload_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warningshield_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warningshield_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warningshield_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warningshield_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warningshield_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warningshield_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
